from tkinter import*
from tkinter import ttk
from tkinter import messagebox
a=Tk()
a.title("LOGIN")
p=PhotoImage(file="blood.png")
l=Label(a,image=p)
l.place(relwidth=1,relheight=1)
l1=Label(a,text="WELCOME TO OUR PREDICTION",bg="black",fg="white",font=("times",40))
l1.pack(fill="x")
f=Frame(a,bd=6,bg="black")
l2=Label(f,text="USERNAME:",bg="white",fg="black")
l2.grid(row=0,column=0)
e=Entry(f)
e.grid(row=0,column=1,padx=3)
l3=Label(f,text="PASSWORD:",bg="white",fg="black")
l3.grid(row=1,column=0,pady=3)
e1=Entry(f)
e1.grid(row=1,column=1,padx=3)
def login():
    if(e.get()=="S" and e1.get()=="1"):
        messagebox.showinfo("LOGINED","SUCCESSFULLY LOGINED")
        b=Tk()
        b.title("BLOOD GROUPS")
        b.config(bg="white")
        L2=Label(b,text="SELECT THE DETAILS TO PREDICT",bg="grey",fg="white",font=("times",30))
        L2.pack(fill="x")
        f=Frame(b,bd=8,bg="black")
        f.pack()
        l=Label(f,text="SELECT PATERNAL'S BLOOD GROUP:",bg="white",fg="black")
        l.grid(row=0,column=0,pady=3)
        c=ttk.Combobox(f,width=10)
        c["value"]=["A","B","O"]
        c.grid(row=0,column=1,padx=3)
        l1=Label(f,text="SELECT MATERNAL'S BLOOD GROUP:",bg="white",fg="black")
        l1.grid(row=1,column=0,pady=3)
        c1=ttk.Combobox(f,width=10)
        c1["value"]=["A","B","O"]
        c1.grid(row=1,column=1,padx=3)
        def submit():
            if(c.get()=="A" and c1.get()=="A"):
                d=Tk()
                d.title("PREDICTED")
                d.config(bg="Black")
                d2=Frame(d)
                d2.pack()
                l=Label(d2,text="YOUR BLOOD GROUP MIGHT BE:",bg="red",fg="black",font=("times",30))
                l.grid(row=0,column=0)
                L=Label(d2,text="'A'",bg="red",fg="black",font=("times",30))
                L.grid(row=0,column=1)
                d1=Frame(d)
                d1.pack()
                L1=Label(d1,text="DISCLAMIER:",font=("times",20))
                L1.grid(row=3,column=0)
                l1=Label(d1,text="DO NOT USE THIS PREDICTOR FOR PATERNITY CONFIRMATION,CONSULT A PROFESSIONAL TO DO SO..........",font=("times",20))
                l1.grid(row=3,column=1)
                l12=Label(d1,text="USE THIS CAUTIOUSLY AS A PREDICTIVE TOOL ONLY..........",font=("times",20))
                l12.grid(row=4,column=1)
                
            elif(c.get()=="O" and c1.get()=="A"):
                f=Tk()
                f.title("PREDICTED")
                f.config(bg="Black")
                f1=Frame(f)
                f1.pack()
                l=Label(f1,text="YOUR BLOOD GROUP MIGHT BE:",bg="red",fg="black",font=("times",30))
                l.grid(row=0,column=0)
                L=Label(f1,text="'A'",bg="red",fg="black",font=("times",30))
                L.grid(row=0,column=1)
                d1=Frame(f)
                d1.pack()
                L1=Label(d1,text="DISCLAMIER:",font=("times",20))
                L1.grid(row=3,column=0)
                l1=Label(d1,text="DO NOT USE THIS PREDICTOR FOR PATERNITY CONFIRMATION,CONSULT A PROFESSIONAL TO DO SO..........",font=("times",20))
                l1.grid(row=3,column=1)
                l12=Label(d1,text="USE THIS CAUTIOUSLY AS A PREDICTIVE TOOL ONLY..........",font=("times",20))
                l12.grid(row=4,column=1)
            elif(c.get()=="A" and c1.get()=="O"):
                h=Tk()
                h.title("PREDICTED")
                h.config(bg="Black")
                h1=Frame(h)
                h1.pack()
                l=Label(h1,text="YOUR BLOOD GROUP MIGHT BE:",bg="red",fg="black",font=("times",30))
                l.grid(row=0,column=0)
                L=Label(h1,text="'A'",bg="red",fg="black",font=("times",30))
                L.grid(row=0,column=1)
                d1=Frame(h)
                d1.pack()
                L1=Label(d1,text="DISCLAMIER:",font=("times",20))
                L1.grid(row=3,column=0)
                l1=Label(d1,text="DO NOT USE THIS PREDICTOR FOR PATERNITY CONFIRMATION,CONSULT A PROFESSIONAL TO DO SO..........",font=("times",20))
                l1.grid(row=3,column=1)
                l12=Label(d1,text="USE THIS CAUTIOUSLY AS A PREDICTIVE TOOL ONLY..........",font=("times",20))
                l12.grid(row=4,column=1)
            elif(c.get()=="B" and c1.get()=="B"):
                H=Tk()
                H.title("PREDICTED")
                H.config(bg="Black")
                H1=Frame(H)
                H1.pack()
                l=Label(H1,text="YOUR BLOOD GROUP MIGHT BE:",bg="red",fg="black",font=("times",30))
                l.grid(row=0,column=0)
                L=Label(H1,text="'B'",bg="red",fg="black",font=("times",30))
                L.grid(row=0,column=1)
                d1=Frame(H)
                d1.pack()
                L1=Label(d1,text="DISCLAMIER:",font=("times",20))
                L1.grid(row=3,column=0)
                l1=Label(d1,text="DO NOT USE THIS PREDICTOR FOR PATERNITY CONFIRMATION,CONSULT A PROFESSIONAL TO DO SO..........",font=("times",20))
                l1.grid(row=3,column=1)
                l12=Label(d1,text="USE THIS CAUTIOUSLY AS A PREDICTIVE TOOL ONLY..........",font=("times",20))
                l12.grid(row=4,column=1)
            elif(c.get()=="O" and c1.get()=="B"):
                V=Tk()
                V.title("PREDICTED")
                V.config(bg="Black")
                V1=Frame(V)
                V1.pack()
                l=Label(V1,text="YOUR BLOOD GROUP MIGHT BE:",bg="red",fg="black",font=("times",30))
                l.grid(row=0,column=0)
                L=Label(V1,text="'B'",bg="red",fg="black",font=("times",30))
                L.grid(row=0,column=1)
                d1=Frame(V)
                d1.pack()
                L1=Label(d1,text="DISCLAMIER:",font=("times",20))
                L1.grid(row=3,column=0)
                l1=Label(d1,text="DO NOT USE THIS PREDICTOR FOR PATERNITY CONFIRMATION,CONSULT A PROFESSIONAL TO DO SO..........",font=("times",20))
                l1.grid(row=3,column=1)
                l12=Label(d1,text="USE THIS CAUTIOUSLY AS A PREDICTIVE TOOL ONLY..........",font=("times",20))
                l12.grid(row=4,column=1)
            elif(c.get()=="B" and c1.get()=="O"):
                V1=Tk()
                V1.title("PREDICTED")
                V1.config(bg="Black")
                V11=Frame(V1)
                V11.pack()
                l=Label(V11,text="YOUR BLOOD GROUP MIGHT BE:",bg="red",fg="black",font=("times",30))
                l.grid(row=0,column=0)
                L=Label(V11,text="'B'",bg="red",fg="black",font=("times",30))
                L.grid(row=0,column=1)
                d1=Frame(V1)
                d1.pack()
                L1=Label(d1,text="DISCLAMIER:",font=("times",20))
                L1.grid(row=3,column=0)
                l1=Label(d1,text="DO NOT USE THIS PREDICTOR FOR PATERNITY CONFIRMATION,CONSULT A PROFESSIONAL TO DO SO..........",font=("times",20))
                l1.grid(row=3,column=1)
                l12=Label(d1,text="USE THIS CAUTIOUSLY AS A PREDICTIVE TOOL ONLY..........",font=("times",20))
                l12.grid(row=4,column=1)
            elif(c.get()=="O" and c1.get()=="O"):
                V2=Tk()
                V2.title("PREDICTED")
                V2.config(bg="Black")
                V21=Frame(V2)
                V21.pack()
                l=Label(V21,text="YOUR BLOOD GROUP MIGHT BE:",bg="red",fg="black",font=("times",30))
                l.grid(row=0,column=0)
                L=Label(V21,text="'O'",bg="red",fg="black",font=("times",30))
                L.grid(row=0,column=1)
                d1=Frame(V2)
                d1.pack()
                L1=Label(d1,text="DISCLAMIER:",font=("times",20))
                L1.grid(row=3,column=0)
                l1=Label(d1,text="DO NOT USE THIS PREDICTOR FOR PATERNITY CONFIRMATION,CONSULT A PROFESSIONAL TO DO SO..........",font=("times",20))
                l1.grid(row=3,column=1)
                l12=Label(d1,text="USE THIS CAUTIOUSLY AS A PREDICTIVE TOOL ONLY..........",font=("times",20))
                l12.grid(row=4,column=1)
            elif(c.get()=="A" and c1.get()=="B"):
                V4=Tk()
                V4.title("PREDICTED")
                V4.config(bg="Black")
                V41=Frame(V4)
                V41.pack()
                l=Label(V41,text="YOUR BLOOD GROUP MIGHT BE:",bg="red",fg="black",font=("times",30))
                l.grid(row=0,column=0)
                L=Label(V41,text="'AB'",bg="red",fg="black",font=("times",30))
                L.grid(row=0,column=1)
                d1=Frame(V4)
                d1.pack()
                L1=Label(d1,text="DISCLAMIER:",font=("times",20))
                L1.grid(row=3,column=0)
                l1=Label(d1,text="DO NOT USE THIS PREDICTOR FOR PATERNITY CONFIRMATION,CONSULT A PROFESSIONAL TO DO SO..........",font=("times",20))
                l1.grid(row=3,column=1)
                l12=Label(d1,text="USE THIS CAUTIOUSLY AS A PREDICTIVE TOOL ONLY..........",font=("times",20))
                l12.grid(row=4,column=1)
            elif(c.get()=="B" and c1.get()=="A"):
                V3=Tk()
                V3.title("PREDICTED")
                V3.config(bg="Black")
                V31=Frame(V3)
                V31.pack()
                l=Label(V31,text="YOUR BLOOD GROUP MIGHT BE:",bg="red",fg="black",font=("times",30))
                l.grid(row=0,column=0)
                L=Label(V31,text="'AB'",bg="red",fg="black",font=("times",30))
                L.grid(row=0,column=1)
                d1=Frame(V3)
                d1.pack()
                L1=Label(d1,text="DISCLAMIER:",font=("times",20))
                L1.grid(row=3,column=0)
                l1=Label(d1,text="DO NOT USE THIS PREDICTOR FOR PATERNITY CONFIRMATION,CONSULT A PROFESSIONAL TO DO SO..........",font=("times",20))
                l1.grid(row=3,column=1)
                l12=Label(d1,text="USE THIS CAUTIOUSLY AS A PREDICTIVE TOOL ONLY..........",font=("times",20))
                l12.grid(row=4,column=1)
            else:
                messagebox.showinfo("404 ERROR","WE COULD NOT PREDICT IT,SORRY")
        b5=Button(f,text="SUBMIT",bg="violet",fg="black",command=submit)
        b5.grid(row=2,column=1)
    else:
        messagebox.showinfo("404 ERROR","PLEASE ENTER CORRECTLY")
b=Button(f,text="LOGIN",bg="green",fg="black",command=login)
b.grid(row=2,column=1)
f.place(x=500,y=500)

